language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    
  licenses:
    - '.+'
    - 'android-sdk-preview-license-52d11cd2-.+'
    - 'android-sdk-license-c81a61d9-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - echo yes | android update sdk --no-ui --all --filter platform-tools,tools
  - echo yes | android update sdk --no-ui --all --filter build-tools-25.0.2
  - echo yes | android update sdk --no-ui --all --filter android-24

script:
   - android update sdk --no-ui --filter build-tools-25.0.2,android-25,extra-android-m2repository
   - ./gradlew clean test
